### ISSUE TITLE
提示缺一个java-merge-sort的库

### ISSUE THREAD

**Issue by geeseek** [sing1ee/dict_build#1]
eclipse下编译运行提示缺 java-merge-sort

**Comment by sing1ee** [comment]
是在哪一步，缺少这个呢？

**Comment by geeseek** [comment]
就编译的时候，好像是缺fasterxml库？  提示com.fasterxml.sort import 错误

**Comment by sing1ee** [comment]
我是通过maven导入的，你可以先mvn install一下
