### ISSUE TITLE
如何用python接口进行调用

### ISSUE THREAD

**Issue by wwtBlog** [sing1ee/dict_build#11]
rt

**Comment by sing1ee** [comment]
这个程程序，可以脱离java打包，python调用的需求是？

2017-05-26 11:01 GMT+08:00 wwtBlog <notifications@github.com>:

**Comment by wwtBlog** [comment]
可以在任何场景下进行python接口的调用

**Comment by sing1ee** [comment]
这个程序目前是一次性，批量运行的

**Comment by wwtBlog** [comment]
能不能运行一个文件夹下多个文件，如何在python下进行调用能说清楚点吗

**Comment by sing1ee** [comment]
1. 一个文件夹下的多个文件，需要你改一下我的代码了。
1. 目前不支持python的接口

**Comment by wwtBlog** [comment]
你之前提到过的打包，那能不能整理成jar包然后用python调用呢？

**Comment by sing1ee** [comment]
这个我考虑下，看看怎么Python调用一下

2017-05-30 17:43 GMT+08:00 wwtBlog <notifications@github.com>:

**Comment by withr** [comment]
在python里运行shell命令不就可以了？

**Comment by sing1ee** [comment]
bingo @withr
