### ISSUE TITLE
参数能调整吗？语料比较小，跑出来都没有什么结果~

### ISSUE THREAD

**Issue by Harrd** [sing1ee/dict_build#17]
150m的数据跑出来只有150个词。。

**Comment by sing1ee** [comment]
通常来讲，不需要调的。如果要调整都在FastBuild这个类里面。你是什么语料，方便我调试下么

**Comment by Harrd** [comment]
不好意思，不能发出来哦，我这个主要是计算机相关文章，很多中英文术语，中英文混合的比较多，好像算法还没有对英文进行处理

**Comment by sing1ee** [comment]
难怪如此了，目前没有对英文做处理，主要是中文词的抽取。
