### ISSUE TITLE
FastBuilder里面的 googlecode  RadixTree 包应该怎么引入

### ISSUE THREAD

**Issue by bingzi** [sing1ee/dict_build#18]
import com.googlecode.concurrenttrees.radix.ConcurrentRadixTree;
import com.googlecode.concurrenttrees.radix.RadixTree;
import com.googlecode.concurrenttrees.radix.node.concrete.DefaultCharArrayNodeFactory;

package dict.build下的FastBuilder 的这个3个包应该怎么导入，我是菜鸟，求指导！

**Comment by sing1ee** [comment]
直接运行 ./gradlew build就可以啦

2017-08-08 11:39 GMT+08:00 bingzi <notifications@github.com>:
