### ISSUE TITLE
输出结果分别代表什么意思

### ISSUE THREAD

**Issue by hechenghai** [sing1ee/dict_build#23]
输出结果除了词，词频，自由运用程度（左右邻信息熵的最小值），凝固程度还有什么？
以及源码中words.data文件的输出应该是词，凝固程度，自由运用程度，并没有词频也没有多出来的那一列，所以好像实际运行的代码并不是源码。

**Comment by sing1ee** [comment]
代码是一致的，readme中给出的例子，都是用github上的代码跑出来的。

在 2017年9月22日 下午1:59，hechenghai <notifications@github.com>写道：

**Comment by hechenghai** [comment]
哦哦，谢谢。那您能说一下输出每一列都代表什么意思吗？

**Comment by sing1ee** [comment]
词频，互信息，左右熵，位置成词概率

**Comment by hechenghai** [comment]
好的谢谢。。。
