### ISSUE TITLE
请问一下第五列位置成词概率是怎么算出来的?

### ISSUE THREAD

**Issue by JokerDu** [sing1ee/dict_build#25]
位置成词概率是你这里说的：最后输出 词,词频,互信息,左右熵,位置成词概率.

**Comment by sing1ee** [comment]
@JokerDu 统计的搜狗词库。

**Comment by withr** [comment]
刚好我也想问这个问题，你们给出详细一些的解释？比如公式啊，例子什么的？先谢了，这个软件真赞。

**Comment by sing1ee** [comment]
某个字出现在次首的次数 / 某个字出现的总次数，以此类推。

**Comment by JokerDu** [comment]
@sing1ee 你算出来的某个字的成词概率有三个，好像计算的是一个词中的字分别在S,M,E的三个概率，最后计算这个词的概率，是取了
`pp = Math.min(posProp.get(w.subSequence(0, 1))[0], posProp.get(w.subSequence(w.length() - 1, w.length()))[2]);`来作为这个词的成词概率是这样吗？能不能稍微解释一下呢，谢谢你~

**Comment by lintiven49** [comment]
@JokerDu 你这个研究出来了吗?我也是这一点一直看不懂= =
还有计算 pmi 的时候 `double pf = freq * total / max;`
这个分子为什么是 `freq * total`?

**Comment by sing1ee** [comment]
@lintiven49 @JokerDu 时间也比较久了，看看介绍中的文章。

**Comment by sing1ee** [comment]
我也再看看回想一下 @JokerDu @lintiven49

**Comment by eromoe** [comment]
我也想知道 成词概率 是怎么算的， 我本来以为是拿已经训练好的模型进行判断，不过没看到模型文件。

**Comment by eromoe** [comment]
> 统计的搜狗词库。
大概理解了，事先用带有词频的词库 计算出一个词中的字分别在S,M,E的三个概率。也就是成词概率有3个概率。直接取里面最小的。

最后都是按照 人工设的阈值来过滤。想问下这个阈值是怎么确定的？

**Comment by sing1ee** [comment]
@eromoe 👍。这个阈值的设定，就是通过统计数据的分布，实际中也可以适当调整

**Comment by yongzhuo** [comment]
搜狗词库在什么地方？

**Comment by sing1ee** [comment]
网上可以下载 @yongzhuo 
过了几年了，我建议采用更全的词库，效果会更好。
