### ISSUE TITLE
words_sort.data 无结果

### ISSUE THREAD

**Issue by Volong** [sing1ee/dict_build#29]
我通过命令行运行，words_sort.data 没有信息。见图
![info](https://user-images.githubusercontent.com/9137053/34761455-e3b0cf70-f61e-11e7-9d35-e316964becf4.png)

但是我把代码 git 下来，在编译器里面运行，words_sort.data 却是有结果的。数据文件都是[同一份](https://pan.baidu.com/s/1pL3L15T)。

**Comment by ChingO22** [comment]
能不能指教一下，在哪个编译器运行的，怎么在运行？

**Comment by Volong** [comment]
Eclipse 
dict.build.Main 这个类

**Comment by sing1ee** [comment]
大家有java开发背景么？

2018-01-10 17:14 GMT+08:00 yihailong <notifications@github.com>:

**Comment by yongzhuo** [comment]
Main函数没有输入.txt文件的地方啊；那个Builder才有；但是没有结果；只有ngram_left.data有数据

**Comment by sing1ee** [comment]
Main是有的啊，需要传入参数，指定原始文件的位置，才能运行

2018-01-29 17:30 GMT+08:00 yongzhuo <notifications@github.com>:

**Comment by yongzhuo** [comment]
可以啦，谢谢，问一句，新增的dic新词，是append，是存在什么地方的哇?

**Comment by yongzhuo** [comment]
words_sort.data没有数据，words.data有数据；我的测试有什么问题，帮我看看，谢谢；见图：
![93xc hzs qswz zih5qk1](https://user-images.githubusercontent.com/31341349/35544791-1d8cc4fa-05a7-11e8-98bc-5452eca4c947.png)

**Comment by sing1ee** [comment]
目测没看出来什么问题，你debug一下，告诉我结果？

或者你把数据给我，我跑一下

**Comment by adrianhust** [comment]
words_sort.data 和 words.data 都没有数据  sort_ngram_left.data 也没有，不知道什么原因

**Comment by sing1ee** [comment]
中间的数据文件呢

2018-04-11 13:48 GMT+08:00 adrianhust <notifications@github.com>:

**Comment by sing1ee** [comment]
有什么异常信息么？
你先小批量跑一下

2018-04-17 15:22 GMT+08:00 adrianhust <notifications@github.com>:

**Comment by shenlan211314** [comment]
请问是如何解决的呢？ 
我现在是windows/linux运行后words_sort.data无结果，words.data有结果。但是mac下都有结果。

在dict.build.Main下修改filepath为训练文件路径也不可以呢，看调用的数据没有数据处理步骤。

**Comment by sing1ee** [comment]
试一下最新的代码

**Comment by bhan97** [comment]
@sing1ee 你好，我用你最新的代码，txt文件右下角
![图片](https://user-images.githubusercontent.com/38981805/56132533-cc71a100-5fbc-11e9-812b-4b66b6f5f9fd.png)的运行时间特别短，words_sort.data和words.data都是空，而且其他各个结果文件里都是乱码韩文繁体字什么的。
运行过程下方：
![图片](https://user-images.githubusercontent.com/38981805/56132964-eb246780-5fbd-11e9-9e1b-68f5e6dd029c.png)

只有txt文件右下角
![图片](https://user-images.githubusercontent.com/38981805/56132636-135f9680-5fbd-11e9-815b-76f1d4fc282f.png)
运行正常。

**Comment by sing1ee** [comment]
@bhan97 那应该就是编码的问题了，确认下，是最新的代码么？以及看下输入文件的字符集？

**Comment by bhan97** [comment]
@sing1ee 代码是最新的 之前删掉重新下载了 文件最后改动日期都是4月8号 输入文件都是 纯中文简体

**Comment by sing1ee** [comment]
@bhan97 字符集是指中文的编码，utf8，还是gbk？

**Comment by bhan97** [comment]
@sing1ee 哦哦 明白了 非常感谢！！

**Comment by bhan97** [comment]
@sing1ee 你好，问下为什么 命令行跑出来生成文件没有问题，用eclipse跑dict.build.Main 文件几乎是空的
![图片](https://user-images.githubusercontent.com/38981805/57578488-1ec0b780-74c0-11e9-8097-2201966e7733.png)
![图片](https://user-images.githubusercontent.com/38981805/57578489-1f594e00-74c0-11e9-8a0d-b5b3a9dcd8b0.png)
