### ISSUE TITLE
请问pos_prop.txt文件的使用含义？

### ISSUE THREAD

**Issue by frederic89** [sing1ee/dict_build#3]
我正在研读这个项目的源代码，请问sing1ee，项目中的pos_prop.txt来源是训练的结果吗？那三列数值应该代表什么含义呢？因为我有看到了下面的代码：
`pp = Math.min(posProp.get(w.subSequence(0, 1))[0], posProp.get(w.subSequence(w.length() - 1, w.length()))[2]);`

我在研究新词抽取方面的事情，望与您进一步沟通。

**Comment by sing1ee** [comment]
pos_prop.txt 是统计的结果，我如果没记错，是来自搜狗词库的统计结果，三列数值分别是单字出现在词首，词中，词尾的概率。作为一个判断的纬度。

**Comment by sing1ee** [comment]
@frederic89 你有看到运行结束的效果么？pos_prop.txt可以用更大的词典进行统计，不过效果上也差不多。

**Comment by frederic89** [comment]
sing1ee 非常感谢你，我觉得这个项目在小语料任务中 有很好的应用潜力 从你的项目中学到了很多

**Comment by sing1ee** [comment]
@frederic89 谢谢
