### ISSUE TITLE
关于 pmi 的计算

### ISSUE THREAD

**Issue by Volong** [sing1ee/dict_build#31]
@sing1ee 你好，为什么 pmi 的计算方式是这个样子呢？
```java
double pf = freq * total / max;
double pmi = Math.log(pf) / Math.log(2);
```

**Comment by sing1ee** [comment]
@Volong 时间比较久了。这个应该就是PMI的计算公式

**Comment by Volong** [comment]
@sing1ee PMI 的公式是这样的：
![image](https://user-images.githubusercontent.com/9137053/43904924-7d0a666e-9c22-11e8-81a9-74051bc373bf.png)

所以我才搞不清这里这样写的原因是什么。

**Comment by sing1ee** [comment]
@Volong 四年钱的事情了，我需要看看代码。
你也可以试试按照你给公式的计算，验证一下结果。

**Comment by Volong** [comment]
@sing1ee 我理解你为什么这样做了。之前不理解的地方在于为什么乘以 `total`。我把 `pf` 的值输出看了一下，发现数值特别小，所以乘以一个 `total` 是为了将结果扩大的吧。

**Comment by sing1ee** [comment]
👍

**Comment by Zhouzhiling** [comment]
啊这么一说我也懂了，在同一次分类任务中total可以看作一个常数。感谢！

**Comment by DouMiaoO-Oo** [comment]
> 
> 
> @sing1ee 我理解你为什么这样做了。之前不理解的地方在于为什么乘以 `total`。我把 `pf` 的值输出看了一下，发现数值特别小，所以乘以一个 `total` 是为了将结果扩大的吧。

@Volong 
![图片](https://user-images.githubusercontent.com/13816863/62767227-cef58a80-bac6-11e9-89ac-483a4d3e7994.png)
上面是我的推导，我觉得作者的公式没有问题呀。

上述公式的TeX：
$$PMI(x, y) = log\dfrac{P(x, y)}{P(x)P(y)}=log\dfrac{\dfrac{freq(x, y)}{total} }{\dfrac{freq(x)}{total} \dfrac{freq(y)}{total} }  = log\dfrac{freq(x, y) \times total }{freq(x) \times freq(y) }$$

**Comment by sing1ee** [comment]
@DouMiaoO-Oo 是这样的，total消掉了一个。
