### ISSUE TITLE
words.data和words_sort.data为空

### ISSUE THREAD

**Issue by liyuanzhe** [sing1ee/dict_build#33]
如题，为什么程序执行完，words.data和words_sort.data为空

**Comment by shaohualuan** [comment]
这边修改编码格式之后，运行可以生成相关的文件，但是文件内容都为空，大家有相似的问题吗

**Comment by sing1ee** [comment]
比较奇怪，可以贴一下原始的数据文件，我来试试么

**Comment by shenlan211314** [comment]
我也有同样的问题，linux/windows下words_sort.data是空的，mac下有结果。
查看linux windows确认文件都是utf-8格式。

**Comment by sing1ee** [comment]
@liyuanzhe @shaohualuan 试一下最新的代码
