### ISSUE TITLE
最终的排序只按词频合理吗

### ISSUE THREAD

**Issue by zhaoweiwang** [sing1ee/dict_build#34]
互信息、左右熵、位置成词概率用来排序似乎比词频好一些

**Comment by sing1ee** [comment]
这里排序可以灵活调整

**Comment by zhaoweiwang** [comment]
[root@g4 rerult]# ll
总用量 31945456
-rw-r--r--. 1 root root           0 11月  7 16:11 freq_ngram.data
-rw-r--r--. 1 root root 13236662420 11月  7 16:09 merge_w3_doc.db
-rw-r--r--. 1 root root 19475470740 11月  7 16:58 ngram.data
-rw-r--r--. 1 root root           0 11月  7 16:58 ngram_sort.data
[root@g4 rerult]# ll
总用量 31945456
-rw-r--r--. 1 root root           0 11月  7 16:11 freq_ngram.data
-rw-r--r--. 1 root root 13236662420 11月  7 16:09 merge_w3_doc.db
-rw-r--r--. 1 root root 19475470740 11月  7 16:58 ngram.data
-rw-r--r--. 1 root root           0 11月  7 16:58 ngram_sort.data

===========
跑10G以上的语料库，上面没动静了，这是OOM了吗

**Comment by sing1ee** [comment]
如果OOM了，会有异常。CPU是满的么

**Comment by zhaoweiwang** [comment]
上百G的服务器开6G JAVA_OPTS下OOM了，改成2G重跑下
没动静的反而跑起来了，一天一夜已过去...

**Comment by sing1ee** [comment]
这么大的数据，我确实没测试过。
看下cpu，内存，硬盘的负载？

**Comment by zhaoweiwang** [comment]
后面都挂了，改成逐个小语料跑。楼主可以对自己的代码压力测试一下

**Comment by sing1ee** [comment]
多谢反馈，确实之前没跑过这么大的语料

>
