### ISSUE TITLE
total 与freq的计算问题

### ISSUE THREAD

**Issue by xv44586** [sing1ee/dict_build#39]
1.PMI=log(P(x,y)/(p(x)p(y)), p(x,y)=freq/N, p(x)=freq_x/N => PMI=log(freq*N/(freq_x*freq*y)),而total=word_frag_count,这里感觉应该是取错了，应该是语料内所以的“字”的数量；
2.freq用的是右侧前缀树的总和，这样会少记录当词右侧没有内容的情况，如词出现在句子末尾（吧/呢）直接统计word的freq是不是会更好？

**Comment by sing1ee** [comment]
时间确实够久远了。
我建议，你可以直接修改代入值，看看效果是不是会更好。

xv44586 <notifications@github.com> 于2019年7月30日周二 下午5:49写道：

**Comment by sing1ee** [comment]
@xv44586 非常希望你能做一个实验，如果效果更好，欢迎PR

**Comment by DouMiaoO-Oo** [comment]
> 
> 
> 2.freq用的是右侧前缀树的总和，这样会少记录当词右侧没有内容的情况，如词出现在句子末尾（吧/呢）直接统计word的freq是不是会更好？

@xv44586 作者在每个ngram的后面位置都补充了一个`$`: `sen = "$" + sen + "$";`
所以可以统计到结尾的ngram。

**Comment by sing1ee** [comment]
@DouMiaoO-Oo thx。
