### ISSUE TITLE
关于 isChinese 的字符编码范围

### ISSUE THREAD

**Issue by DouMiaoO-Oo** [sing1ee/dict_build#41]
```
public static boolean isChinese(char a) { 
	     int v = (int)a; 
	     return (v >=19968 && v <= 171941); 
	}
```
其中的数值判断条件换算成十六进制是 [0x4e00, 0x29fa5]，  请问这个右区间为什么等于0x29fa5呢。 我查了一下中文Unicode编码的右区间应该是 `0x9fa5`（十进制40869），不知道您代码中的`0x29fa5`是刻意为之还是笔误？

**Comment by sing1ee** [comment]
的确如此。thx。
