### ISSUE TITLE
抽取结果与示例不太一致

### ISSUE THREAD

**Issue by Old-Su** [sing1ee/dict_build#44]
使用<金瓶梅>进行测试发现, 实际结果中"西门庆"不是词频最高的词, 而且没有出现"西门庆",
而是出现了诸如"见西门庆","向西门庆","西门庆进"等词. 
作者有时间的话能否给指导一下?

**Comment by Old-Su** [comment]
还有就是想问下, 如果不以词频排序, 想以互信息或左右熵来排序的话, 有什么方式可以指定吗? 因为没有Java基础, 是写python的, 作者有时间的话烦请指导一下.

**Comment by sing1ee** [comment]
目前还没有提供参数，指定排序。不过你可以linux shell，自己处理下

**Comment by sing1ee** [comment]
> 作者有时间的话能否给指导一下?

这个和你的输入的文本有关系。我想你找的内容，应该是不对的。

**Comment by sing1ee** [comment]
> 作者有时间的话能否给指导一下?

这个和你的输入的文本有关系。我想你找的内容，应该是不对的。

**Comment by Old-Su** [comment]
嗯嗯. 理解了. 感谢.
