### ISSUE TITLE
found a boundary condition problem

### ISSUE THREAD

**Issue by DBtxy** [sing1ee/dict_build#45]
https://github.com/sing1ee/dict_build/blob/master/src/main/java/dict/build/Builder.java#L268

你好，拜读了你的源码之后，我发现一个边界问题，有点疑惑

When sameWord is not null and pause == false and curr == null, the loop will  be terminated, so the string in sameWord  will be missed. 

简单的说就是sameWord 在循环跳出之后并不是空的，会导致一些字符串被丢失。。。

**Comment by sing1ee** [comment]
@DBtxy 六年了，可能我对这个代码，还没有你熟悉的。我看看先~

**Comment by DBtxy** [comment]
> @DBtxy 六年了，可能我对这个代码，还没有你熟悉的。我看看先~

哈哈，好的好的，不急

**Comment by sing1ee** [comment]
> > @DBtxy 六年了，可能我对这个代码，还没有你熟悉的。我看看先~
> 
> 哈哈，好的好的，不急

现在跑起来，没有问题吧

**Comment by DBtxy** [comment]
> > > @DBtxy 六年了，可能我对这个代码，还没有你熟悉的。我看看先~
> > 
> > 
> > 哈哈，好的好的，不急
> 
> 现在跑起来，没有问题吧

跑应该是没有问题的，后面逻辑把这个边界问题产生的影响覆盖住了，可能就几个字符串的差异

**Comment by sing1ee** [comment]
够细心，我抽空看看，然后交流交流。

**Comment by DBtxy** [comment]
其实我还有一个问题哈，直接切出来的 ngram的量级非常大，即使采用外部文件归并排序的话也会很久，排序结果计算freq也很久，为什么一边切，一边构建dict，统计ngram，最后把ngarm 及其频次输出到文件中，再排序的话量级会减少很多。这块我一直有个疑问哈？

**Comment by DBtxy** [comment]
> 其实我还有一个问题哈，直接切出来的 ngram的量级非常大，即使采用外部文件归并排序的话也会很久，排序结果计算freq也很久，为什么不一边切，一边构建dict，统计ngram，最后把ngarm 及其频次输出到文件中，再排序的话量级会减少很多。这块我一直有个疑问哈？

哦哦，看到你的fastbuilder了，666
