### ISSUE TITLE
跑400MB的文本数据会出现错误

### ISSUE THREAD

**Issue by Vanqingyu** [sing1ee/dict_build#5]
是否无法处理大规模数据？

**Comment by sing1ee** [comment]
@Vanqingyu 我测试下，因为是用的基于磁盘的排序，所以数据量大了，仅仅是时间问题。能贴出来错误么？400MB也不算大的。

**Comment by sing1ee** [comment]
@Vanqingyu 方便共享一下文本么？

**Comment by Vanqingyu** [comment]
目前只能看到报的在treenode上的错误

**Comment by Vanqingyu** [comment]
能否加你的QQ

**Comment by Vanqingyu** [comment]
文本里面含有英文，是否会造成影响？

**Comment by Vanqingyu** [comment]
https://pan.baidu.com/s/1eRFdJJ8
这是其中一部分文本数据

**Comment by sing1ee** [comment]
@Vanqingyu 314235397 QQ
