### ISSUE TITLE
关于并行调用

### ISSUE THREAD

**Issue by SpecterHi** [sing1ee/dict_build#6]
master分支的程序，处理数据时产生的中间状态的临时文件和最终的分词文件都和原始数据文件在同一个路径之下。
这样一来，如果数据目录有很多文件，希望能够通过shell来并行调用您的程序的时候就会很麻烦。

目前我们的想法是，写shell脚本来调度：

- 对于源文件夹中的每个数据文件都创建一个独特的新文件夹
- 然后将数据文件移入
- 再调用您的程序
- 处理完毕之后再将数据挪回来
- 并将最终的分词结果文件重命名，统一移到特定的位置

不知道有没有什么简单的方法能够实现修改源程序来规避目前无法对同一文件夹下的多个文件同时进行处理的状况？
我们尝试修改了FastBuilder.java多处涉及到路径的部分，但是没能成功~

然后刚才才看到parallel这个分支，不过似乎和master是完全一致的？

**Comment by sing1ee** [comment]
parallel 这个分支主要是性能考虑，还没有开始开发。

在 2017年4月10日 下午2:04，SpecterHi <notifications@github.com>写道：

**Comment by sing1ee** [comment]
你说的这个并发，目的是？

**Comment by SpecterHi** [comment]
就是我们现在有大量的语料，数百个文档，单个大小从几百M到几十G不等，存放在几个文件夹之中
实测程序执行的时候对服务器资源占用率并不高，因此想加速这一过程。

**Comment by sing1ee** [comment]
这个可以改参数的，归并排序的时候，有几个参数，可以调试一下

在 2017年4月10日 下午3:04，SpecterHi <notifications@github.com>写道：
