### ISSUE TITLE
请问内部使用的数据结构

### ISSUE THREAD

**Issue by chiyang10000** [sing1ee/dict_build#7]
你好，
请问统计串频和左右熵使用的是什么算法？
感觉要高效并且节省内存，要使用trie和nagao？

大概想借助你的代码做一个语料信息的统计。
但是懒得认真看代码了。

**Comment by sing1ee** [comment]
之前用的是ternary search tree，但是数据量大之后由问题，就改为radix tree

**Comment by chiyang10000** [comment]
你好，请问位置成词概率是个什么东西？

**Comment by sing1ee** [comment]
@chiyang10000 统计单个字在词的首位，尾位，以及中间的概率。

**Comment by chiyang10000** [comment]
感谢

**Comment by DouMiaoO-Oo** [comment]
不太了解radix tree， 我只是好奇想请教一下，radix tree在词这种很短的字符串上，效果会比tries tree好么？

**Comment by sing1ee** [comment]
@DouMiaoO-Oo 这个效果是综合的。目前radix tree在内存是上应该是胜出的。

不过代码是有很大的空间的，具体数据结构的比较，也没有深入过。

如果有更好的实现，欢迎PR

**Comment by sing1ee** [comment]
@DouMiaoO-Oo [In computer science, a radix tree (also radix trie or compact prefix tree) is a data structure that represents a space-optimized trie (prefix tree) in which each node that is the only child is merged with its parent. ](https://en.wikipedia.org/wiki/Radix_tree)
