### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by chiyang10000** [sing1ee/dict_build#9]
排序之前 writeter应该flush，不然排序后的文件会缺行

**Comment by sing1ee** [comment]
你提一个pull request吧，谢谢。

2017-05-16 10:32 GMT+08:00 chiyang10000 <notifications@github.com>:

**Comment by chiyang10000** [comment]
@sing1ee 我在你的代码上面改得比较多，不好merge进去。
刚刚还发现一个bug就是genLeft和genRight的最后应该还要把stat里面的内容输出出去，会缺少一些数据的左右熵。

**Comment by sing1ee** [comment]
赞赞的，不能merge也没关系，有用就好。
